### ISSUE TITLE
this is wrong because Shadow Diffusion(J) is used mask.

### ISSUE THREAD

**Issue by AnasHXH** [xw-hu/Unveiling-Deep-Shadows#2]
![image](https://github.com/user-attachments/assets/0f49480d-9754-4371-b958-ca69cdb02b66)

this is wrong because Shadow Diffusion(J) is used mask.

**Comment by xw-hu** [comment]
Please find the Table 1 in the paper of ShadowDiffusion(J), which is “Y. Jin, W. Yang, W. Ye, Y. Yuan, and R. T. Tan, “Shadowdiffusion: Diffusion-based shadow removal using classifier-driven attention and structure preservation,” arXiv preprint arXiv:2211.08089, 2022. It clearly indicates this method does not use shadow mask.
![image](https://github.com/user-attachments/assets/15908483-3b43-45c4-87ef-9eccef3dfc6a)

**Comment by AnasHXH** [comment]
Yes, you are right. Thank you
